/**
 * Typed contracts of the ranking / match history API.
 * Shared by the client (Axios + TanStack Query) and the mock server (MSW),
 * so both sides always agree on paths, payloads and errors.
 */

import type { EndReason } from '../game/sim/types'

/** The settings that make two matches comparable in the ranking. */
export interface MatchConfig {
  sessionSeconds: number
  spawnIntervalSeconds: number
}

/** One finished match. It is both a history entry and a ranking entry. */
export interface MatchRecord {
  /** Generated by the client when the match starts; also the idempotency key. */
  matchId: string
  playerId: string
  playerName: string
  /** ISO 8601 date of the end of the match. */
  finishedAt: string
  score: number
  /** Seconds of active play (pauses excluded). */
  durationSeconds: number
  endReason: EndReason
  config: MatchConfig
}

export interface RankingEntry extends MatchRecord {
  /** 1-based position among matches with the same config. */
  rank: number
}

export interface Page<T> {
  items: T[]
  /** 1-based. */
  page: number
  pageSize: number
  totalItems: number
  totalPages: number
}

/** GET /api/ranking?page&pageSize&sessionSeconds&spawnIntervalSeconds */
export interface RankingQuery {
  config: MatchConfig
  page: number
  pageSize: number
}

/** GET /api/players/:playerId/matches?page&pageSize (newest first) */
export interface HistoryQuery {
  playerId: string
  page: number
  pageSize: number
}

/**
 * PUT /api/matches/:matchId — idempotent registration.
 * 201 + created: true the first time; 200 + created: false when the match was
 * already registered (a retry), returning the stored record. Never duplicates.
 */
export interface RegisterMatchResponse {
  record: MatchRecord
  created: boolean
}

/** Body of every 4xx/5xx response. */
export interface ApiErrorBody {
  error: string
  message: string
}

export const API_ROUTES = {
  ranking: '/api/ranking',
  playerMatches: '/api/players/:playerId/matches',
  match: '/api/matches/:matchId',
} as const

export const apiPaths = {
  ranking: () => API_ROUTES.ranking,
  playerMatches: (playerId: string) => `/api/players/${encodeURIComponent(playerId)}/matches`,
  match: (matchId: string) => `/api/matches/${encodeURIComponent(matchId)}`,
}

export const PAGE_SIZE = 5
export const MAX_PAGE_SIZE = 50

/**
 * Ranking order (deterministic tie-break):
 * 1. higher score; 2. shorter duration (same score, faster); 3. earlier date
 * (who got there first); 4. match id, so two runs never order differently.
 */
export function compareForRanking(a: MatchRecord, b: MatchRecord): number {
  return (
    b.score - a.score ||
    a.durationSeconds - b.durationSeconds ||
    a.finishedAt.localeCompare(b.finishedAt) ||
    a.matchId.localeCompare(b.matchId)
  )
}

export function sameConfig(a: MatchConfig, b: MatchConfig): boolean {
  return a.sessionSeconds === b.sessionSeconds && a.spawnIntervalSeconds === b.spawnIntervalSeconds
}
